### ISSUE TITLE
Carola change broke the app

### ISSUE THREAD

**Issue by Alisu** [guillep/git-tutorial#11]
The update of the readme.md totally broke it.

**Comment by hogoww** [comment]
Same, Carolina can't be trusted

**Comment by carolahp** [comment]
You are jealous because my PR was accepted!

**Comment by ClotildeToullec** [comment]
Works for me, maybe you don't know how to use it.

**Comment by hogoww** [comment]
it broke my very advanced project :(

**Comment by Alisu** [comment]
Then can we have a tutorial on how to use it ?
I think advance stuff like this should be explained.

**Comment by hogoww** [comment]
Thank you :)
